services:
  - type: web
    name: clipai
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SITE_URL
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PRICE_ID
        sync: false
      - key: STRIPE_WEBHOOK_SECRET
        sync: false
      - key: ADSENSE_PUBLISHER_ID
        sync: false
